### ISSUE TITLE
DB connections should not span API calls

### ISSUE THREAD

**Issue by smr547** [GeoscienceAustralia/agdc#13]
More a suggestion than a question...

The query API currently returns a generator inviting applications to iterate over Tiles and Cells. The generator will hold a database connection (and cursor) open until iteration is complete. Connections and cursors are heavyweight objects (particularly for the DB server). Application Tile processing may be long running and connections may be held open for long periods of time. 

The concern is that this approach will not scale on HPC where there may be many thousands of applications instances each slowly iterating sets of Tiles. The single DB server can become stressed having to maintain many long-duration cursors. Also connection limits may be reached resulting in denial of service to application instances.

Suggest using

```python
    cursor.execute(sql, params)
    tiles = []
       
   for record in cursor:
       tiles.append(Tile.from_db_record(record))

   conn.close()
   return tiles
```
Instead of

```python
    for record in result_generator(cursor):
        yield Tile.from_db_record(record)
```

The former has the advantage of ensuring that cursors and connections are explicitly closed and, more importantly, have very short life spans on the DB server. The memory and time cost of transporting the full result set to the application host ought to be modest given our Tile numbers and the lightweight nature of Tile instances.

**Comment by alex-ip** [comment]
I agree completely with Steve. Aside from the client side overheads, maintaining open transactions over a long time potentially causes the connection pooler to block other queries until they are closed. 

In general, transactions should be kept short and sharp, with database activity effectively front-loaded before slow data processing activity. The old stacker does this by iterating through the query result set to create a data structure and then immediately closing the DB connection, much along the lines of Steve's suggestion. 

On 29 January 2015 03:31:35 GMT+11:00, Steven Ring <notifications@github.com> wrote:
>More a suggestion than a question...
>
>The query API currently returns a generator inviting applications to
>iterate over Tiles and Cells. The generator will hold a database
>connection (and cursor) open until iteration is complete. Connections
>and cursors are heavyweight objects (particularly for the DB server).
>Application Tile processing may be long running and connections may be
>held open for long periods of time. 
>
>The concern is that this approach will not scale on HPC where there may
>be many thousands of applications instances each slowly iterating sets
>of Tiles. The single DB server can become stressed having to maintain
>many long-duration cursors. Also connection limits may be reached
>resulting in denial of service to application instances.
>
>Suggest using
>
>```python
>    cursor.execute(sql, params)
>    tiles = []
>       
>   for record in cursor:
>       tiles.append(Tile.from_db_record(record))
>
>   conn.close()
>   return tiles
>```
>Instead of
>
>```python
>    for record in result_generator(cursor):
>        yield Tile.from_db_record(record)
>```
>
>The former has the advantage of ensuring that cursors and connections
>are explicitly closed and, more importantly, have very short life spans
>on the DB server. The memory and time cost of transporting the full
>result set to the application host ought to be modest given our Tile
>numbers and the lightweight nature of Tile instances. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/GeoscienceAustralia/agdc/issues/13

-- 
Sent from my mini-tablet. Please excuse my brevity and possible typos.

**Comment by simonoldfield** [comment]
The API support 2 styles of query - a single use open connection generator style via `list_cells_as_generator` and `list_tiles_as_generator` OR a read and retrieve everything style via `list_cells_as_list` and `list_tiles_as_list`.  The idea being you can choose which style suits your use.

My catch-cry for API land is that there is no such thing as _one size fits all_. :smile:

**Comment by smr547** [comment]
In API land there are some sizes you probably don't want to offer.

We will have no control over how the developers design their datacube
applications. Almost certainly, if a function is offered, it will be used
in many, often novel and unexpected ways.  Offer a developer a generator
they will use it. If the generator holds the database connection open then
their apps will exhaust the connection pool and everyone will be very
unhappy.

I don't think we should offer the generator option in the api.

Someone once said, "Just because you can doesn't mean you should"

On Fri, Jan 30, 2015 at 10:46 AM, Simon Oldfield <notifications@github.com>
wrote:

> The API support 2 styles of query - a single use open connection generator
> style via list_cells_as_generator and list_tiles_as_generator OR a read
> and retrieve everything style via list_cells_as_list and
> list_tiles_as_list. The idea being you can choose which style suits your
> use.
>
> My catch-cry for API land is that there is no such thing as *one size
> fits all*. [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoscienceAustralia/agdc/issues/13#issuecomment-72127952>
> .
>



-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268
f: +61 2 6100 9273
s: stevering

**Comment by alex-ip** [comment]
Once again: agreed. There should be no reason to leave transactions 
hanging open and tying up DB connections in a read-only scenario. Just 
get what you need and disconnect - we're not talking massive result sets 
here.

**Comment by smr547** [comment]
What are our current connection limits on the AGDC Postgres server?

**Comment by smr547** [comment]
Of course, we can offer "connection holding generators" if we don't have a central database server so issue #14 is relevant to the discussion.

**Comment by alex-ip** [comment]
There is a lot of headroom in the existing configurations - I didn't 
fiddle with them a lot when I originally configured them, so there is 
definite room for tweaking.

The connection poolers are currently set up to allow up to 1000 
concurrent transaction requests of which only 100 can be served 
concurrently, the rest blocking until transactions finish and their 
connections become available. (See my earlier comments about the 
undesirability of long-running transactions)

Each connection pooler is configured in /etc/pgbouncer/pgbouncer.ini as 
follows

    ; total number of clients that can connect
    *max_client_conn = 1000*
    ; default pool size.  20 is good number when transaction pooling
    ; is in use, in session pooling it needs to be the number of
    ; max clients you want to handle at any moment
    *default_pool_size = 100*
    ; how many additional connection to allow in case of trouble
    ;reserve_pool_size = 5
    ; if a clients needs to wait more than this many seconds, use
    reserve pool
    ;reserve_pool_timeout = 3

Each individual DB server is currently configured in 
/var/lib/pgsql/9.3/data/postgresql.conf as follows:

    *max_connections = 100* # (change requires restart)
    # Note:  Increasing max_connections costs ~400 bytes of shared
    memory per
    # connection slot, plus lock space (see max_locks_per_transaction).
    #superuser_reserved_connections = 3     # (change requires restart)

We have 16GB of memory on each of the DB server VMs, so we should be 
able to bump the max_connections up into the thousands without breaking 
a sweat. If you want to play with this, get Wenjun to spin up another DB 
server (it's easy) and set up some load testing against it. I suspect 
you'll find the query times sill still be dwarfed by the data processing 
times, even with the current config.

BTW: I opted to use pgBouncer as the connection pooler because of its 
small footprint, transparency and easy setup. If we were to use pgPool 
(http://www.pgpool.net/mediawiki/index.php/Main_Page), we could 
load-balance against multiple servers, possibly even spinning them up 
dynamically as required. We haven't even scratched the surface as far as 
scaling the Postgres DBs up.

HTH,

Alex.

**Comment by alex-ip** [comment]
I forgot to add: The reason we have the DB server OpenStack VMs was 
because we needed to get the hell of the shared Postgres server at the 
NCI (we couldn't even use PostGIS on it). AFAIK, the only time WOfS 
processing was ever limited by the DB connections was back when we were 
on that shared server, which had a hard connection limit of 100, beyond 
which subsequent connection requests were simply refused. Correct me if 
I'm wrong, but I am not aware of the DB query causing any job failures 
in large-scale processing since the dedicated servers with connection 
poolers were set up. I certainly wasn't told about it if it did occur.

Also, the original WOfS code used multiple Stacker instances in a way 
they were never intended to be used, with all the attendant munging of 
data structures and redundant checks for the existence of N-S overlaps, 
and this took hours to do. Since the cataloguing of the N-S mosaic 
tiles, a single query can return references to all of the required tiles 
in a matter of seconds, compared to the hours required to process them.

I'm more than happy for someone to investigate other indexing DB 
solutions, but I honestly don't really think this needs to be a high 
priority right now.

**Comment by simonoldfield** [comment]
Final comments....

The way the generator works is that it retrieves the result in chunks.  The database connection can be closed once the final chunk has been read - and so if the total number is under the chunk size it can be closed immediately.

Also as well as the `_as_generator` and `_as_list` methods `_to_file` methods are also provided so that the whole result set dumped straight to a file (internal to the API) and then the API can present that as a stream of records just as if it was coming straight from the database so the client code is the same.

I think between all these we should be pretty much covered - certainly for the reasonably foreseeable future.

I'm closing this now so we can move onto more pressing matters.
