### ISSUE TITLE
Allow retrieve pixel drill tool to operate over satellites with non-identical bands

### ISSUE THREAD

**Issue by simonoldfield** [GeoscienceAustralia/agdc#24]
For example over LS5, LS7 and LS8 for NBAR.
The options that immediately spring to mind for dealing with this are:
1. only output the common bands
2. output the superset of bands with no value for datasets that don't have the band

**Comment by wenjunwu** [comment]
Can we support both options and allow a user to make a choice?

**Comment by woodcockr** [comment]
From the API reviews and thoughts I've had thus far option 2 appears to be far the most common option. In part I believe because you are already dealing with missing values so some more don't hurt. In a mixed satellite environment this will also be more the norm as the new satellites which aren't continuation missions start collecting data.
If folks want "common bands" they can restrict the choice of satellite to those with common bands in the data selection filter, so no need for option 1.

**Comment by simonoldfield** [comment]
The *Retrieve Pixel Time Series* tool now supports the `--bands-all` and `--bands-common` command line arguments.

With the `--bands-all` argument all possible band are output, with a **NULL** value in instances where the band is N/A.

With the `--bands-common` argument the only bands common to all data sets are output.

The default behaviour is `--bands-all`.
